#!/usr/bin/env python3
"""coach-onboarding-poller.py — Polls webhook customers and runs onboarding.

Every 5 minutes:
1. Check /opt/data/state/customers.json for new (onboarded: false) customers
2. For each, send WhatsApp informed-consent
3. Create entry in /opt/data/state/coaching-customers.json
4. Mark customer onboarded=true
5. Write brief to coach-onboarding/outbox/
"""
import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

STATE_DIR = Path("/opt/data/state")
CUSTOMERS_FILE = STATE_DIR / "customers.json"
COACHING_FILE = STATE_DIR / "coaching-customers.json"
ONBOARDING_OUTBOX = Path("/opt/data/agents/coach-onboarding/outbox")
WHATSAPP_HELPER = "/opt/data/scripts/whatsapp-send.py"


def load_json(path, default=None):
    if default is None:
        default = {}
    if not path.exists():
        return default
    return json.loads(path.read_text())


def save_json(path, data):
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2, default=str))
    tmp.replace(path)


def send_whatsapp(recipient, message):
    r = subprocess.run(
        ["python3", WHATSAPP_HELPER, recipient, message, "--sender", "coach-onboarding"],
        capture_output=True, text=True, timeout=30
    )
    try:
        result = json.loads(r.stdout)
        return result.get("status") == "sent"
    except:
        return False


def run_onboarding(customer):
    customer_id = customer["customer_id"]
    name = customer.get("name") or "Customer"
    tier = customer.get("tier", "S")
    vertical = customer.get("vertical", "unknown")
    language = customer.get("language", "es")
    
    send_whatsapp("ivan", f"[coach-onboarding] New customer: {name} ({tier}, {customer['currency']} {customer.get('amount')}, vertical={vertical}). Consent message queued. Reply APPROVE to send.")
    
    coaching = load_json(COACHING_FILE, {"customers": {}, "last_updated": None})
    
    coaching["customers"][customer_id] = {
        "name": name,
        "email": customer.get("email"),
        "tier": tier,
        "vertical": vertical,
        "language": language,
        "source": customer.get("source"),
        "amount": customer.get("amount"),
        "currency": customer.get("currency"),
        "onboarding_started": datetime.now(timezone.utc).isoformat(),
        "onboarding_step": "day-1-consent",
        "consent_sent": True,
        "consent_approved": False,
    }
    coaching["last_updated"] = datetime.now(timezone.utc).isoformat()
    
    save_json(COACHING_FILE, coaching)
    return True


def main():
    customers_data = load_json(CUSTOMERS_FILE, {"customers": []})
    
    new_count = 0
    for customer in customers_data["customers"]:
        if not customer.get("onboarded"):
            run_onboarding(customer)
            customer["onboarded"] = True
            customer["onboarded_at"] = datetime.now(timezone.utc).isoformat()
            new_count += 1
    
    if new_count > 0:
        save_json(CUSTOMERS_FILE, customers_data)
        ONBOARDING_OUTBOX.mkdir(parents=True, exist_ok=True)
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        brief = ONBOARDING_OUTBOX / f"{today}.md"
        brief.write_text(f"""# Coach Onboarding Brief - {today}

Onboarded {new_count} new customers from webhook events.

## Customers processed
{chr(10).join(f"- {c['customer_id']} ({c['tier']}, {c['source']})" for c in customers_data["customers"] if c.get("onboarded"))}

## Next steps
- Day 3 (3 days from now): Send goals intake
- Day 7: Send baseline metrics form
- Day 10: Schedule first GROW session

## Sources
- /opt/data/scripts/webhook-receiver.py (Factor 11)
- /opt/data/state/customers.json
- /opt/data/state/coaching-customers.json

---
*Generated by coach-onboarding poller (Factor 11)*
""")
        print(f"Onboarded {new_count} customers; brief written to {brief}")
    else:
        print("No new customers to onboard")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="""Script description not available""")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen")
    parser.add_argument("--verbose", action="store_true", help="Verbose output")
    args = parser.parse_args()

