#!/usr/bin/env python3
"""Generate PROMPT-monitor.md files for agents missing them.

Built as Phase 28 R6 (A4 - 28 missing monitors).

Reads each agent's PROMPT.md, extracts key info (state files, key fields),
and generates a templated PROMPT-monitor.md.

Usage:
    python3 scripts/generate-monitors.py           # generate all missing
    python3 scripts/generate-monitors.py --dry-run # show what would be created
    python3 scripts/generate-monitors.py --only <agent-name>
"""
import argparse
import re
from pathlib import Path

# --- AIW_ROOT path bootstrap (DEMIURGE-098) ---
import sys as _sys_bootstrap_098
from pathlib import Path as _Path_bootstrap_098
_PY_PATHS_ROOT = _Path_bootstrap_098(__file__).resolve().parent.parent
if str(_PY_PATHS_ROOT) not in _sys_bootstrap_098.path:
    _sys_bootstrap_098.path.insert(0, str(_PY_PATHS_ROOT))
from _paths import AGENTS, AIW_ROOT
# --- end bootstrap ---


ROOT = AGENTS

MONITOR_TEMPLATE = """# {agent_name}-monitor — Watchdog for {agent_name}

> Watchdog for {agent_name}. Read-only.

## Purpose

Watch the state files below and flag signals that {agent_name} health is degrading. Lead agent is `{agent_name}`.

## Files watched

{file_table}

## Metrics watched

{metrics}

## Threshold rules

{thresholds}

## Alert routing

- **CRITICAL / HIGH** — append to `/opt/data/agents/state/coord.json:decisions_for_ivan[]`.
- **MEDIUM** — append to parallel notes file at `/opt/data/agents/{agent_path}/monitor-notes/YYYY-MM-DD.md` (do NOT mutate state files — schemas are `additionalProperties: false`).
- **LOW** — silent.

## Run procedure

1. Read watched files via `cat ... | python3 -m json.tool`.
2. Validate via `python3 /opt/data/agents/scripts/schema-validate-write.py --strict` for any with schemas. Invalid → HIGH escalation.
3. Evaluate every metric → fire per routing table.

## Suggested cron schedule

Default: daily `0 9 * * *` (morning check before Ivan's review).

## Hard stops

- DO NOT modify any watched file.
- DO NOT auto-fix issues — flag only.

## CHANGELOG

- v0.1.0 (2026-09-01): generated by `scripts/generate-monitors.py` (Phase 28 R6).
"""


def extract_state_files(prompt_text: str, agent_path: str) -> list[str]:
    """Extract state file paths mentioned in PROMPT.md."""
    # Look for paths like /opt/data/agents/state/<dept>/<file>.json
    pattern = r"/opt/data/agents/state/[\w/-]+\.json"
    return sorted(set(re.findall(pattern, prompt_text)))


def extract_metrics(prompt_text: str, state_files: list[str]) -> list[str]:
    """Generate plausible metrics from state file names."""
    metrics = []
    for sf in state_files:
        basename = Path(sf).stem
        # Common metrics per file
        if basename == "kiki":
            metrics.extend([
                "kiki.streak_days",
                "kiki.last_lesson_at",
            ])
        elif basename == "kiki-prep":
            metrics.extend([
                "kiki-prep.last_run",
                "kiki-prep.open_stuck.length",
            ])
        elif basename == "coord":
            metrics.extend([
                "coord.last_run",
                "coord.decisions_for_ivan.length",
            ])
        else:
            metrics.append(f"{basename}.last_run")
    return metrics[:5]


def generate_thresholds(metrics: list[str]) -> str:
    """Generate threshold rules from metrics."""
    rows = []
    for m in metrics:
        if "length" in m:
            rows.append(f"| `{m}` | > 10 | **HIGH** |")
        elif "last_run" in m:
            rows.append(f"| `{m}` | null or > 7 days ago | **HIGH** |")
        elif "streak" in m:
            rows.append(f"| `{m}` | < 7 | **MEDIUM** |")
        else:
            rows.append(f"| `{m}` | check | **MEDIUM** |")
    return "\n".join(rows) if rows else "| (no specific thresholds — flag anomalies) | — | **MEDIUM** |"


def generate_for_agent(agent_dir: Path, dry_run: bool = False) -> str:
    """Generate PROMPT-monitor.md for one agent. Returns status string."""
    agent_name = agent_dir.name
    prompt_path = agent_dir / "PROMPT.md"
    if not prompt_path.exists():
        return f"SKIP {agent_name}: no PROMPT.md"
    monitor_path = agent_dir / "PROMPT-monitor.md"
    if monitor_path.exists():
        return f"SKIP {agent_name}: monitor already exists"

    prompt_text = prompt_path.read_text()
    agent_path = str(agent_dir.relative_to(ROOT))
    state_files = extract_state_files(prompt_text, agent_path)
    if not state_files:
        # Default: monitor the agent's own state dir
        state_files = [f"/opt/data/agents/state/{agent_path.split('/')[0]}/{agent_name}.json"]
    file_table = "| File | Schema |\n|------|--------|"
    for sf in state_files:
        schema_name = Path(sf).stem + ".schema.json"
        file_table += f"\n| `{sf}` | `{schema_name}` |"

    metrics = extract_metrics(prompt_text, state_files)
    thresholds = generate_thresholds(metrics)

    content = MONITOR_TEMPLATE.format(
        agent_name=agent_name,
        agent_path=agent_path,
        file_table=file_table,
        metrics="\n".join(f"{i+1}. `{m}`" for i, m in enumerate(metrics)),
        thresholds=thresholds,
    )

    if not dry_run:
        monitor_path.write_text(content)
        return f"OK {agent_name}"
    return f"DRY-RUN {agent_name}"


def main():
    parser = argparse.ArgumentParser(description="Generate PROMPT-monitor.md for missing agents")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--only", help="Only generate for this agent name")
    args = parser.parse_args()

    # Find all PROMPT.md without PROMPT-monitor.md
    all_prompts = [p.parent for p in ROOT.rglob("PROMPT.md")]
    have_monitor = {p.parent for p in ROOT.rglob("PROMPT-monitor.md")}
    missing = [p for p in all_prompts if p not in have_monitor]

    if args.only:
        missing = [p for p in missing if p.name == args.only]

    print(f"Found {len(missing)} agents needing PROMPT-monitor.md")
    for agent_dir in sorted(missing):
        result = generate_for_agent(agent_dir, dry_run=args.dry_run)
        print(f"  {result}")
    print(f"\nTotal: {len(missing)} processed")


if __name__ == "__main__":
    main()
