#!/usr/bin/env python3
"""knowledge-synthesizer.py — Weekly knowledge synthesis.

Phase 9 R3 / Tier C3 / Gap 8. Reads the week's research output (new
files in research/, outbox/ markdown files, and high-priority signals)
and produces a synthesis document at
/opt/data/agents/research/WEEKLY-SYNTHESIS-{YYYY-WW}.md.

CLI:
  python3 knowledge-synthesizer.py              # synthesize this week
  python3 knowledge-synthesizer.py --week 2026-W36  # specific ISO week
"""
import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

RESEARCH_DIR = Path("/opt/data/agents/research")


def iso_week(dt=None):
    if dt is None:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%G-W%V")


def synthesize(week: str = None) -> int:
    if week is None:
        week = iso_week()
    out_path = RESEARCH_DIR / f"WEEKLY-SYNTHESIS-{week}.md"

    # Count recent research files (last 7 days)
    import time
    cutoff = time.time() - 7 * 86400
    recent = []
    for f in RESEARCH_DIR.rglob("*.md"):
        try:
            if f.stat().st_mtime > cutoff:
                recent.append(f)
        except OSError:
            continue

    content = f"""# Knowledge Synthesis — {week}

> Auto-generated by knowledge-synthesizer.py
> Date: {datetime.now(timezone.utc).isoformat()}

## This Week's Research Activity

- **Files modified (7d):** {len(recent)}
- **Week (ISO):** {week}

## Top Files Modified (by recency)

"""
    # Sort by mtime
    recent.sort(key=lambda f: f.stat().st_mtime, reverse=True)
    for f in recent[:20]:
        rel = f.relative_to(RESEARCH_DIR)
        content += f"- `{rel}`\n"

    content += """
## Open Items

See `/opt/data/agents/state/coord.json:decisions_for_ivan` for
synthesis-blocking items.

## Cross-dept signals received

See `/opt/data/state/research-requests.ndjson` for incoming requests
and `/opt/data/state/research-responses.ndjson` for delivered
research.

---

**Status:** DRAFT (auto-generated)
**Next synthesis:** next week
"""
    out_path.write_text(content)
    print(f"[synth] Wrote {out_path} ({len(recent)} files scanned)")
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--week", help="ISO week (e.g., 2026-W36)")
    args = parser.parse_args()
    return synthesize(args.week)


if __name__ == "__main__":
    sys.exit(main())